# Generated by Django 3.2.19 on 2025-07-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('initial', 'Initial'), ('final', 'Final')], default='initial', max_length=10)),
                ('grade_value', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(choices=[('VOID', 'Void'), ('OPEN', 'Open'), ('FINAL', 'Final')], default='VOID', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('grade_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='grades.gradeassignment')),
            ],
        ),
    ]
