# Generated by Django 3.2.19 on 2025-07-01 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiongrade',
            name='grade_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_grades', to='grades.gradeassignment'),
        ),
        migrations.AddField(
            model_name='gradeassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='course.course'),
        ),
        migrations.AddField(
            model_name='gradeassignment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gradeassignment',
            unique_together={('student', 'course', 'semester', 'submission_type')},
        ),
    ]
