# Generated by Django 3.2.19 on 2025-06-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeassignment',
            name='submission_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('final', 'Final')], default='initial', max_length=10),
        ),
    ]
