# Generated by Django 3.2.19 on 2025-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
