# Generated by Django 3.2.19 on 2025-07-01 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='representatives',
            field=models.ManyToManyField(limit_choices_to={'role': 'representative'}, related_name='institutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
