# Generated by Django 3.2.19 on 2025-04-22 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0002_institution_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='representative',
        ),
        migrations.AddField(
            model_name='institution',
            name='representatives',
            field=models.ManyToManyField(limit_choices_to={'role': 'representative'}, related_name='institution', to=settings.AUTH_USER_MODEL),
        ),
    ]
