# Generated by Django 3.2.19 on 2025-04-23 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0003_auto_20250422_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='representatives',
            field=models.ManyToManyField(limit_choices_to={'role': 'representative'}, related_name='institutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
