# Generated by Django 3.2.19 on 2025-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_gradeassignment_submission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeassignment',
            name='submission_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('final', 'Final')], max_length=10),
        ),
    ]
