# Generated by Django 3.2.19 on 2025-06-22 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20250620_1011'),
        ('grades', '0003_alter_gradeassignment_submission_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradeassignment',
            unique_together={('student', 'course', 'semester', 'submission_type')},
        ),
    ]
