# Generated by Django 3.2.19 on 2025-06-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20250624_1306'),
        ('grades', '0004_alter_gradeassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeassignment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_assignments', to='course.enrollment'),
        ),
        migrations.AlterField(
            model_name='gradeassignment',
            name='submission_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('final', 'Final')], default='initial', max_length=10),
        ),
    ]
