version: '3.8'

services:
  #Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:4000
    depends_on:
      - backend

  #Backend
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=clearsky
      - DB_PASSWORD=securepassword
      - DB_NAME=clearsky
    depends_on:
      - postgres

  #Database
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=clearsky
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=clearsky
    ports:
      - "5432:5432"

volumes:
    postgres_data:
