# Generated by Django 3.2.19 on 2025-07-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('initial_submission_date', models.CharField(blank=True, max_length=50, null=True)),
                ('final_submission_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
