# Generated by Django 3.2.19 on 2025-07-01 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_course_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(limit_choices_to={'role': 'instructor'}, related_name='instructor_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
