# Generated by Django 3.2.19 on 2025-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_submission_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='initial_submission_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
