# Generated by Django 3.2.19 on 2025-06-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20250624_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeassignment',
            name='enrollment',
        ),
    ]
