# Generated by Django 3.2.19 on 2025-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_registration_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
