# Generated by Django 3.2.19 on 2025-05-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_student_registration_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_registration_id',
            new_name='registration_id',
        ),
    ]
